TEST = 12312

HOST = '127.0.0.1'
PORT = 21567
BUFSIZ = 4096
ADDR = (HOST, PORT)



def isID(x):
    return (x < 30) and (x > 0)


ID_REGISTER = 1
ID_LOGIN = 2
ID_PERSONEDIT = 3
ID_ADDRESTAURANT = 4
ID_GETRESTAURANT = 5
ID_DELETERESTAURANT = 6
ID_ADDADDRESS = 7
ID_GETADDRESS = 8
ID_DELETEADDRESS = 9
ID_ADDDISHES = 10
ID_GETDISHES_OWNER = 11
ID_DELETEDISHES = 12
ID_EDITDISHES = 13
ID_SEARCHRESTAURANT = 14
ID_GETDISHES_CUSTOMER = 15
ID_ADDINDENT = 16
ID_GETINDENT_CUSTOMER = 17
ID_FINISHINDENT = 18
ID_GETINDENTDISHES = 19
ID_GETOWNERINDENT = 20
ID_CANCELINDENT = 21