# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_customer(object):
    def setupUi(self, form_customer):
        form_customer.setObjectName("form_customer")
        form_customer.resize(1278, 900)
        self.label_currentIndent = QtWidgets.QLabel(form_customer)
        self.label_currentIndent.setGeometry(QtCore.QRect(30, 80, 101, 41))
        self.label_currentIndent.setObjectName("label_currentIndent")
        self.tableWidget_currentIndent = QtWidgets.QTableWidget(form_customer)
        self.tableWidget_currentIndent.setGeometry(QtCore.QRect(130, 20, 611, 311))
        self.tableWidget_currentIndent.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_currentIndent.setObjectName("tableWidget_currentIndent")
        self.tableWidget_currentIndent.setColumnCount(4)
        self.tableWidget_currentIndent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_currentIndent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_currentIndent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_currentIndent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_currentIndent.setHorizontalHeaderItem(3, item)
        self.tableWidget_currentIndent.horizontalHeader().setDefaultSectionSize(200)
        self.label_pastIndent = QtWidgets.QLabel(form_customer)
        self.label_pastIndent.setGeometry(QtCore.QRect(20, 570, 101, 41))
        self.label_pastIndent.setObjectName("label_pastIndent")
        self.pushButton_edit_phoneNumber = QtWidgets.QPushButton(form_customer)
        self.pushButton_edit_phoneNumber.setGeometry(QtCore.QRect(1090, 40, 141, 28))
        self.pushButton_edit_phoneNumber.setObjectName("pushButton_edit_phoneNumber")
        self.pushButton_order = QtWidgets.QPushButton(form_customer)
        self.pushButton_order.setGeometry(QtCore.QRect(1130, 820, 93, 28))
        self.pushButton_order.setObjectName("pushButton_order")
        self.pushButton_edit_password = QtWidgets.QPushButton(form_customer)
        self.pushButton_edit_password.setGeometry(QtCore.QRect(1090, 100, 141, 28))
        self.pushButton_edit_password.setObjectName("pushButton_edit_password")
        self.pushButton_finish_indent = QtWidgets.QPushButton(form_customer)
        self.pushButton_finish_indent.setGeometry(QtCore.QRect(760, 150, 93, 28))
        self.pushButton_finish_indent.setObjectName("pushButton_finish_indent")
        self.tableWidget_address = QtWidgets.QTableWidget(form_customer)
        self.tableWidget_address.setGeometry(QtCore.QRect(860, 490, 201, 301))
        self.tableWidget_address.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_address.setColumnCount(1)
        self.tableWidget_address.setObjectName("tableWidget_address")
        self.tableWidget_address.setRowCount(0)
        self.tableWidget_address.horizontalHeader().setDefaultSectionSize(200)
        self.pushButton_add_address = QtWidgets.QPushButton(form_customer)
        self.pushButton_add_address.setGeometry(QtCore.QRect(1080, 520, 93, 28))
        self.pushButton_add_address.setObjectName("pushButton_add_address")
        self.pushButton_delete_address = QtWidgets.QPushButton(form_customer)
        self.pushButton_delete_address.setGeometry(QtCore.QRect(1080, 580, 93, 28))
        self.pushButton_delete_address.setObjectName("pushButton_delete_address")
        self.label_address = QtWidgets.QLabel(form_customer)
        self.label_address.setGeometry(QtCore.QRect(920, 840, 55, 16))
        self.label_address.setObjectName("label_address")
        self.tableWidget_pastIndent = QtWidgets.QTableWidget(form_customer)
        self.tableWidget_pastIndent.setGeometry(QtCore.QRect(130, 390, 611, 411))
        self.tableWidget_pastIndent.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_pastIndent.setObjectName("tableWidget_pastIndent")
        self.tableWidget_pastIndent.setColumnCount(4)
        self.tableWidget_pastIndent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pastIndent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pastIndent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pastIndent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pastIndent.setHorizontalHeaderItem(3, item)
        self.tableWidget_pastIndent.horizontalHeader().setDefaultSectionSize(200)
        self.pushButton_cancel_indent = QtWidgets.QPushButton(form_customer)
        self.pushButton_cancel_indent.setGeometry(QtCore.QRect(760, 220, 93, 28))
        self.pushButton_cancel_indent.setObjectName("pushButton_cancel_indent")

        self.retranslateUi(form_customer)
        self.pushButton_edit_phoneNumber.clicked.connect(form_customer.show_change_phoneNumber)
        self.pushButton_order.clicked.connect(form_customer.show_order)
        self.pushButton_edit_password.clicked.connect(form_customer.show_change_password)
        self.pushButton_finish_indent.clicked.connect(form_customer.finish_indent)
        self.pushButton_add_address.clicked.connect(form_customer.add_address)
        self.pushButton_delete_address.clicked.connect(form_customer.delete_address)
        self.tableWidget_currentIndent.cellDoubleClicked['int','int'].connect(form_customer.show_currentIndent)
        self.tableWidget_pastIndent.cellDoubleClicked['int','int'].connect(form_customer.show_pastIndent)
        self.pushButton_cancel_indent.clicked.connect(form_customer.cancel_indent)
        QtCore.QMetaObject.connectSlotsByName(form_customer)

    def retranslateUi(self, form_customer):
        _translate = QtCore.QCoreApplication.translate
        form_customer.setWindowTitle(_translate("form_customer", "Form"))
        self.label_currentIndent.setText(_translate("form_customer", "Current Indent"))
        self.tableWidget_currentIndent.setSortingEnabled(True)
        item = self.tableWidget_currentIndent.horizontalHeaderItem(0)
        item.setText(_translate("form_customer", "Restaurant Name"))
        item = self.tableWidget_currentIndent.horizontalHeaderItem(1)
        item.setText(_translate("form_customer", "Time"))
        item = self.tableWidget_currentIndent.horizontalHeaderItem(2)
        item.setText(_translate("form_customer", "Address"))
        item = self.tableWidget_currentIndent.horizontalHeaderItem(3)
        item.setText(_translate("form_customer", "IID"))
        self.label_pastIndent.setText(_translate("form_customer", "Past Indent"))
        self.pushButton_edit_phoneNumber.setText(_translate("form_customer", "Edit Phone Number"))
        self.pushButton_order.setText(_translate("form_customer", "Order"))
        self.pushButton_edit_password.setText(_translate("form_customer", "Edit Password"))
        self.pushButton_finish_indent.setText(_translate("form_customer", "Finish Indent"))
        self.pushButton_add_address.setText(_translate("form_customer", "Add"))
        self.pushButton_delete_address.setText(_translate("form_customer", "Delete"))
        self.label_address.setText(_translate("form_customer", "Address"))
        self.tableWidget_pastIndent.setSortingEnabled(True)
        item = self.tableWidget_pastIndent.horizontalHeaderItem(0)
        item.setText(_translate("form_customer", "Restaurant Name"))
        item = self.tableWidget_pastIndent.horizontalHeaderItem(1)
        item.setText(_translate("form_customer", "Time"))
        item = self.tableWidget_pastIndent.horizontalHeaderItem(2)
        item.setText(_translate("form_customer", "Address"))
        item = self.tableWidget_pastIndent.horizontalHeaderItem(3)
        item.setText(_translate("form_customer", "IID"))
        self.pushButton_cancel_indent.setText(_translate("form_customer", "Cancel"))

