# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'restaurant.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_form_restaurant(object):
    def setupUi(self, form_restaurant):
        form_restaurant.setObjectName("form_restaurant")
        form_restaurant.resize(789, 1032)
        self.label_indent = QtWidgets.QLabel(form_restaurant)
        self.label_indent.setGeometry(QtCore.QRect(270, 430, 55, 16))
        self.label_indent.setObjectName("label_indent")
        self.label_dishes = QtWidgets.QLabel(form_restaurant)
        self.label_dishes.setGeometry(QtCore.QRect(280, 970, 55, 16))
        self.label_dishes.setObjectName("label_dishes")
        self.tableWidget_indent = QtWidgets.QTableWidget(form_restaurant)
        self.tableWidget_indent.setGeometry(QtCore.QRect(60, 20, 511, 391))
        self.tableWidget_indent.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_indent.setColumnCount(4)
        self.tableWidget_indent.setObjectName("tableWidget_indent")
        self.tableWidget_indent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_indent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_indent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_indent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_indent.setHorizontalHeaderItem(3, item)
        self.tableWidget_dishes = QtWidgets.QTableWidget(form_restaurant)
        self.tableWidget_dishes.setGeometry(QtCore.QRect(60, 540, 511, 391))
        self.tableWidget_dishes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_dishes.setColumnCount(4)
        self.tableWidget_dishes.setObjectName("tableWidget_dishes")
        self.tableWidget_dishes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dishes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dishes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dishes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dishes.setHorizontalHeaderItem(3, item)
        self.pushButton_add_dishes = QtWidgets.QPushButton(form_restaurant)
        self.pushButton_add_dishes.setGeometry(QtCore.QRect(630, 600, 93, 28))
        self.pushButton_add_dishes.setObjectName("pushButton_add_dishes")
        self.pushButton_edit_dishes = QtWidgets.QPushButton(form_restaurant)
        self.pushButton_edit_dishes.setGeometry(QtCore.QRect(630, 690, 93, 28))
        self.pushButton_edit_dishes.setObjectName("pushButton_edit_dishes")
        self.pushButton_delelte_dishes = QtWidgets.QPushButton(form_restaurant)
        self.pushButton_delelte_dishes.setGeometry(QtCore.QRect(630, 770, 93, 28))
        self.pushButton_delelte_dishes.setObjectName("pushButton_delelte_dishes")
        self.pushButton_about_dishes = QtWidgets.QPushButton(form_restaurant)
        self.pushButton_about_dishes.setGeometry(QtCore.QRect(630, 870, 93, 28))
        self.pushButton_about_dishes.setObjectName("pushButton_about_dishes")
        self.pushButton_about_indent = QtWidgets.QPushButton(form_restaurant)
        self.pushButton_about_indent.setGeometry(QtCore.QRect(630, 170, 93, 28))
        self.pushButton_about_indent.setObjectName("pushButton_about_indent")

        self.retranslateUi(form_restaurant)
        self.pushButton_about_indent.clicked.connect(form_restaurant.about_indent)
        self.pushButton_add_dishes.clicked.connect(form_restaurant.add_dishes)
        self.pushButton_edit_dishes.clicked.connect(form_restaurant.edit_dishes)
        self.pushButton_delelte_dishes.clicked.connect(form_restaurant.delete_dishes)
        self.pushButton_about_dishes.clicked.connect(form_restaurant.about_dishes)
        QtCore.QMetaObject.connectSlotsByName(form_restaurant)

    def retranslateUi(self, form_restaurant):
        _translate = QtCore.QCoreApplication.translate
        form_restaurant.setWindowTitle(_translate("form_restaurant", "Form"))
        self.label_indent.setText(_translate("form_restaurant", "Indent"))
        self.label_dishes.setText(_translate("form_restaurant", "Dishes"))
        item = self.tableWidget_indent.horizontalHeaderItem(0)
        item.setText(_translate("form_restaurant", "Account"))
        item = self.tableWidget_indent.horizontalHeaderItem(1)
        item.setText(_translate("form_restaurant", "Address"))
        item = self.tableWidget_indent.horizontalHeaderItem(2)
        item.setText(_translate("form_restaurant", "Time"))
        item = self.tableWidget_indent.horizontalHeaderItem(3)
        item.setText(_translate("form_restaurant", "Cost"))
        item = self.tableWidget_dishes.horizontalHeaderItem(0)
        item.setText(_translate("form_restaurant", "Name"))
        item = self.tableWidget_dishes.horizontalHeaderItem(1)
        item.setText(_translate("form_restaurant", "Kind"))
        item = self.tableWidget_dishes.horizontalHeaderItem(2)
        item.setText(_translate("form_restaurant", "Price"))
        item = self.tableWidget_dishes.horizontalHeaderItem(3)
        item.setText(_translate("form_restaurant", "Sales"))
        self.pushButton_add_dishes.setText(_translate("form_restaurant", "Add Dishes"))
        self.pushButton_edit_dishes.setText(_translate("form_restaurant", "Edit Dishes"))
        self.pushButton_delelte_dishes.setText(_translate("form_restaurant", "Delete Dishes"))
        self.pushButton_about_dishes.setText(_translate("form_restaurant", "About Dishes"))
        self.pushButton_about_indent.setText(_translate("form_restaurant", "About Indent"))

